### ISSUE TITLE
Full-text search with Lunr and 11ty, just general questions

### ISSUE THREAD

**Issue by mattdsteele** [gerwitz/hgc-v12#18]
Hi! I'm interested in building out a little JAMstack app for a side project (a recipe cookbook). I'm looking to build it with Eleventy, and incorporate client-side full-text search.

I'm not very familiar with search libraries, but Lunr looks like a great option from a cursory search, so when I saw https://github.com/11ty/eleventy/issues/522 I thought I'd pick your brain :)

Perusing your code it looks like you're generating the index via https://github.com/gerwitz/hgc-v12/blob/master/src/search/lunr.json.11ty.js and deploying it via https://hans.gerwitz.com/search/lunr.json

So I'm curious, generally did you like this stack? Are there any gotchas I should be aware of before I start down this path, or Lunr resource you found particularly helpful? 

Thanks!

**Comment by gerwitz** [comment]
You have discerned correctly. FWIW, I was previously doing this with Middleman so all the “runtime” code is pretty old.

Here with Eleventy, I’m using a custom collection (cryptically named “content”) in that index builder, but there’s no reason to emulate that if your SSG of choice thinks differently.

I’m pretty happy with it, but figuring it out was a pain. So I hope to write it up for others, but don’t wait for me to just copy!

**Comment by mattdsteele** [comment]
Very cool! I think between this and the search just added into 11ty.io I have enough to cargo-cult :)

Thanks!
