### ISSUE TITLE
rss 404

### ISSUE THREAD

**Issue by drasch** [gerwitz/hgc-v12#30]
https://hans.gerwitz.com/feeds/microblog.rss

(from index: `/`)
```html
   <link rel="alternate" type="application/rss+xml" href="https://hans.gerwitz.com/feeds/microblog.rss" title="Hans's Microblog">
```

**Comment by gerwitz** [comment]
Thanks!

It'd be nice if Netlify gave me (affordable) logs so I could see if anyone's using that old feed URL.
